### PR TITLE
Github Action to Fetch BTD transportation projects (Issue #49)

### PR DESCRIPTION
**Pull request by kellstefan**
Changes include:
-  a NodeJS script (fetch-BTD-projects.js) to download BTD transportation projects file; and
-  a GitHub action that downloads the file weekly by running the script
-  the first automatically dowloaded BTD projects file

The action is currently set to run every Saturday at 8:30 UTC.

### CODE REVIEW

**Comment by thadk** [comment]
Amazing!

**Comment by thadk** [comment]
@kellstefan Would you mind modifying this so that it just overwrites the old file and does not date the file?

Many thanks

**Comment by kellstefan** [comment]
@thadk I modified the script to not include the date in the filename. The BTD projects file should now always save as "BTD_transportation_projects.geojson".

**Comment by thadk** [comment]
Merging and will adjust afterwards in a different issue. Main adjustment needed is to use the public/ folder and maybe to convert `pjson` to `GeoJSON` files using the same tool that this notebook uses: https://observablehq.com/@thadk/arcgis-json-parser-to-geojson.

**Pull request merged**
